project_id = "xadbbuieaxexqguwolkh"


[functions.portal-transparencia]
verify_jwt = false

[functions.inteligencia-v2]
verify_jwt = false

[functions.aneel-insights]
verify_jwt = false

[functions.mapa-insights]
verify_jwt = false

[functions.cross-intelligence]
verify_jwt = false
